# Created with package:mono_repo v2.1.0
language: dart

# Custom configuration
sudo: required
addons:
  chrome: stable
branches:
  only:
    - master

jobs:
  include:
    - stage: analyzer_and_format
      name: "SDK: 2.2.2; PKGS: validations, validations_generator; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: "2.2.2"
      env: PKGS="validations validations_generator"
      script: ./tool/travis.sh dartanalyzer_1
    - stage: analyzer_and_format
      name: "SDK: dev; PKGS: validations, validations_generator; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-warnings --fatal-infos .`]"
      dart: dev
      env: PKGS="validations validations_generator"
      script: ./tool/travis.sh dartfmt dartanalyzer_0
    - stage: unit_test
      name: "SDK: 2.2.2; PKGS: validations, validations_generator; TASKS: `pub run build_runner test --delete-conflicting-outputs -- -p chrome`"
      dart: "2.2.2"
      env: PKGS="validations validations_generator"
      script: ./tool/travis.sh command
    - stage: unit_test
      name: "SDK: dev; PKGS: validations, validations_generator; TASKS: `pub run build_runner test --delete-conflicting-outputs -- -p chrome`"
      dart: dev
      env: PKGS="validations validations_generator"
      script: ./tool/travis.sh command
    - stage: unit_test
      name: "SDK: 2.2.2; PKGS: validations, validations_generator; TASKS: `pub run test`"
      dart: "2.2.2"
      env: PKGS="validations validations_generator"
      script: ./tool/travis.sh test_0
    - stage: unit_test
      name: "SDK: dev; PKGS: validations, validations_generator; TASKS: `pub run test`"
      dart: dev
      env: PKGS="validations validations_generator"
      script: ./tool/travis.sh test_0
    - stage: ensure_build
      name: "SDK: 2.2.2; PKGS: validations, validations_generator; TASKS: `pub run test --run-skipped -t presubmit-only test/ensure_build_test.dart`"
      dart: "2.2.2"
      env: PKGS="validations validations_generator"
      script: ./tool/travis.sh test_1
    - stage: ensure_build
      name: "SDK: dev; PKGS: validations, validations_generator; TASKS: `pub run test --run-skipped -t presubmit-only test/ensure_build_test.dart`"
      dart: dev
      env: PKGS="validations validations_generator"
      script: ./tool/travis.sh test_1

stages:
  - analyzer_and_format
  - unit_test
  - ensure_build

cache:
  directories:
    - "$HOME/.pub-cache"
    - validations/.dart_tool/build
    - validations_generator/.dart_tool/build
